Added check from database
Hronologiya/AQA pull request #28
Opened 2024-10-05 13:09 UTC by Hronologiya

2024-10-05 18:55 UTC, DartBrovsky requested changes

2024-10-05 18:55 UTC, DartBrovsky commented on lesson_24/test_cars.py
> +def authorization() -> Session:
I will no check your homework without Test class definition.

2024-10-06 21:37 UTC, DartBrovsky approved these changes

2024-10-07 10:07 UTC, Hronologiya commented on lesson_24/test_cars.py
> +def authorization() -> Session:
i added test class

2024-10-07 10:08 UTC, merged